### ISSUE TITLE
  Policies for image pull can be configured  container

### ISSUE THREAD

**Issue by ddh-open** [KusionStack/konfig#122]
## Enhancement

**Comment by SparkYuan** [comment]
@ddh-open   According to my understanding, this issue is classified as an enhancement and not a bug. It would be beneficial to include additional details to explain the need for this enhancement.  Exposing the`imagePullPolicy` to a typical Developer is abnormal since this attribute is often set as `IfNotPresent` in most circumstances and Developers do not need to care about it.

**Comment by ddh-open** [comment]
Developer  do not need care about it, but ops can care.   it also used by ops
